target 'XADCustomEventForGoogleMobileAd' do
	use_frameworks!
	project 'XADCustomEventForGoogleMobileAd.xcodeproj'

	pod 'Google-Mobile-Ads-SDK', '~> 7.23'
	pod 'GroundTruthDisplaySDK', '~> 1.1.8'
end
